version: '1.0'

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    networks:
      - postgres


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: igor.silva@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - postgres
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres
